name: CI Pipeline

on:
  push:
    branches: [main]
  pull_request:

jobs:
  build:
    name: Build Firmware
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install ARM GCC Toolchain
        run: |
          sudo apt-get update
          sudo apt-get install -y gcc-arm-none-eabi make

      - name: Build Firmware
        run: make

      - name: Upload ELF Artifact
        uses: actions/upload-artifact@v3
        with:
          name: firmware-elf
          path: firmware.elf

  test:
    name: HIL Test with QEMU
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Download Firmware ELF
        uses: actions/download-artifact@v3
        with:
          name: firmware-elf

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y qemu-system-arm python3 python3-pip pyserial

      - name: Run QEMU and Test Script
        run: |
          echo "Starting QEMU with firmware.elf..."
          qemu-system-arm \
            -M stm32f4-discovery \
            -nographic \
            -serial pty \
            -kernel firmware.elf &
          QEMU_PID=$!
          sleep 2

          echo "Running Python test..."
          python3 test.py

          kill $QEMU_PID || true
