name: CMake CI Pipeline

on:
  push:
    branches: [main]
  pull_request:

jobs:
  build:
    name: Build Project
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake git curl unzip

      - name: Configure with CMake
        run: cmake -S . -B build

      - name: Build Project
        run: cmake --build build -- -j$(nproc)

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: build-folder
          path: build/

  unit_tests:
    name: Run Unit Tests
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Download Build Artifacts
        uses: actions/download-artifact@v3
        with:
          name: build-folder
          path: build

      - name: Install CMake
        run: sudo apt-get update && sudo apt-get install -y cmake

      - name: Run Tests with CTest
        run: |
          cd build
          ctest --output-on-failure --output-junit junit.xml

      - name: Upload Test Report
        uses: actions/upload-artifact@v3
        with:
          name: junit-report
          path: build/junit.xml

  next_phase_integration:
    name: Next Phase Integration
    runs-on: ubuntu-latest
    needs: unit_tests
    if: success() # Only runs if unit_tests succeed
    steps:
      - name: Proceed to Next Phase
        run: echo "Unit tests passed — proceed with integration testing here."
